services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./config:/config
            - prometheus-data:/prometheus
        restart: unless-stopped
        command:
            - "--config.file=/config/prometheus.yaml"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "4000:3000"
        volumes:
            - grafana-data:/var/lib/grafana
        restart: unless-stopped

    node_exporter:
        image: quay.io/prometheus/node-exporter:v1.5.0
        container_name: node_exporter
        command: "--path.rootfs=/host"
        pid: host
        restart: unless-stopped
        volumes:
            - /:/host:ro,rslave

volumes:
    prometheus-data:
        driver: local
    grafana-data:
        driver: local
